[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_ldf_mode = deep+

lib_deps =
    esp32async/AsyncTCP@^3.3.8
    esp32async/ESPAsyncWebServer@^3.7.10
    bblanchon/ArduinoJson@^7.4.2
    adafruit/Adafruit MPU6050@^2.2.6
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit SH110X@^2.1.12
    adafruit/Adafruit BusIO@^1.17.0
    waspinator/AccelStepper@^1.64

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINOJSON_ENABLE_STD_STRING=0
